removed some steps

diff --git a/.github/workflows/build-browser.yml b/.github/workflows/build-browser.yml
--- a/.github/workflows/build-browser.yml
+++ b/.github/workflows/build-browser.yml
@@ -256,196 +256,196 @@ jobs:
           path: browser-source/apps/browser/coverage/coverage-${{ env._BUILD_NUMBER }}.zip
           if-no-files-found: error
 
-  build-safari:
-    name: Build Safari
-    runs-on: macos-11
-    needs:
-      - setup
-      - locales-test
-    env:
-      _BUILD_NUMBER: ${{ needs.setup.outputs.adj_build_number }}
-      _NODE_VERSION: ${{ needs.setup.outputs.node_version }}
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-
-      - name: Set up Node
-        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
-        with:
-          cache: 'npm'
-          cache-dependency-path: '**/package-lock.json'
-          node-version: ${{ env._NODE_VERSION }}
-
-      - name: Print environment
-        run: |
-          node --version
-          npm --version
-
-      - name: Decrypt secrets
-        env:
-          DECRYPT_FILE_PASSWORD: ${{ secrets.DECRYPT_FILE_PASSWORD }}
-        run: |
-          mkdir -p $HOME/secrets
-          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
-            --output "$HOME/secrets/bitwarden-desktop-key.p12" \
-            "$GITHUB_WORKSPACE/.github/secrets/bitwarden-desktop-key.p12.gpg"
-          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
-            --output "$HOME/secrets/appstore-app-cert.p12" \
-            "$GITHUB_WORKSPACE/.github/secrets/appstore-app-cert.p12.gpg"
-          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
-            --output "$HOME/secrets/appstore-installer-cert.p12" \
-            "$GITHUB_WORKSPACE/.github/secrets/appstore-installer-cert.p12.gpg"
-          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
-            --output "$HOME/secrets/devid-app-cert.p12" \
-            "$GITHUB_WORKSPACE/.github/secrets/devid-app-cert.p12.gpg"
-          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
-            --output "$HOME/secrets/devid-installer-cert.p12" \
-            "$GITHUB_WORKSPACE/.github/secrets/devid-installer-cert.p12.gpg"
-          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
-            --output "$HOME/secrets/macdev-cert.p12" \
-            "$GITHUB_WORKSPACE/.github/secrets/macdev-cert.p12.gpg"
-          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
-            --output "$HOME/secrets/bitwarden_desktop_appstore.provisionprofile" \
-            "$GITHUB_WORKSPACE/.github/secrets/bitwarden_desktop_appstore.provisionprofile.gpg"
-
-      - name: Set up keychain
-        env:
-          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
-          DESKTOP_KEY_PASSWORD: ${{ secrets.DESKTOP_KEY_PASSWORD }}
-          DEVID_CERT_PASSWORD: ${{ secrets.DEVID_CERT_PASSWORD }}
-          APPSTORE_CERT_PASSWORD: ${{ secrets.APPSTORE_CERT_PASSWORD }}
-          MACDEV_CERT_PASSWORD: ${{ secrets.MACDEV_CERT_PASSWORD }}
-          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
-        run: |
-          security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
-          security default-keychain -s build.keychain
-          security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
-          security set-keychain-settings -lut 1200 build.keychain
-          security import "$HOME/secrets/bitwarden-desktop-key.p12" -k build.keychain -P $DESKTOP_KEY_PASSWORD \
-            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
-          security import "$HOME/secrets/devid-app-cert.p12" -k build.keychain -P $DEVID_CERT_PASSWORD \
-            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
-          security import "$HOME/secrets/devid-installer-cert.p12" -k build.keychain -P $DEVID_CERT_PASSWORD \
-            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
-          security import "$HOME/secrets/appstore-app-cert.p12" -k build.keychain -P $APPSTORE_CERT_PASSWORD \
-            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
-          security import "$HOME/secrets/appstore-installer-cert.p12" -k build.keychain -P $APPSTORE_CERT_PASSWORD \
-            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
-          security import "$HOME/secrets/macdev-cert.p12" -k build.keychain -P $MACDEV_CERT_PASSWORD \
-            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
-          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASSWORD build.keychain
-
-      - name: NPM setup
-        run: npm ci
-        working-directory: ./
-
-      - name: Build Safari extension
-        run: npm run dist:safari
-        working-directory: apps/browser
-
-      - name: Zip Safari build artifact
-        run: |
-          cd apps/browser/dist
-          zip dist-safari.zip ./Safari/**/build/Release/safari.appex -r
-          pwd
-          ls -la
-
-      - name: Upload Safari artifact
-        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
-        with:
-          name: dist-safari-${{ env._BUILD_NUMBER }}.zip
-          path: apps/browser/dist/dist-safari.zip
-          if-no-files-found: error
-
-  crowdin-push:
-    name: Crowdin Push
-    if: github.ref == 'refs/heads/master'
-    runs-on: ubuntu-22.04
-    needs:
-      - build
-      - build-safari
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-
-      - name: Login to Azure
-        uses: Azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.7
-        with:
-          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
-
-      - name: Retrieve secrets
-        id: retrieve-secrets
-        uses: bitwarden/gh-actions/get-keyvault-secrets@f1125802b1ccae8c601d7c4f61ce39ea254b10c8
-        with:
-          keyvault: "bitwarden-ci"
-          secrets: "crowdin-api-token"
-
-      - name: Upload Sources
-        uses: crowdin/github-action@ee4ab4ea2feadc0fdc3b200729c7b1c4cf4b38f3 # v1.11.0
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          CROWDIN_API_TOKEN: ${{ steps.retrieve-secrets.outputs.crowdin-api-token }}
-          CROWDIN_PROJECT_ID: "268134"
-        with:
-          config: apps/browser/crowdin.yml
-          crowdin_branch_name: master
-          upload_sources: true
-          upload_translations: false
-
-  check-failures:
-    name: Check for failures
-    if: always()
-    runs-on: ubuntu-22.04
-    needs:
-      - cloc
-      - setup
-      - locales-test
-      - build
-      - build-safari
-      - crowdin-push
-    steps:
-      - name: Check if any job failed
-        if: ${{ (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/rc') }}
-        env:
-          CLOC_STATUS: ${{ needs.cloc.result }}
-          SETUP_STATUS: ${{ needs.setup.result }}
-          LOCALES_TEST_STATUS: ${{ needs.locales-test.result }}
-          BUILD_STATUS: ${{ needs.build.result }}
-          SAFARI_BUILD_STATUS: ${{ needs.build-safari.result }}
-          CROWDIN_PUSH_STATUS: ${{ needs.crowdin-push.result }}
-        run: |
-          if [ "$CLOC_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$SETUP_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$LOCALES_TEST_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$BUILD_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$SAFARI_BUILD_STATUS" = "failure" ]; then
-              exit 1
-          elif [ "$CROWDIN_PUSH_STATUS" = "failure" ]; then
-              exit 1
-          fi
-
-      - name: Login to Azure - Prod Subscription
-        uses: Azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.7
-        if: failure()
-        with:
-          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
-
-      - name: Retrieve secrets
-        id: retrieve-secrets
-        if: failure()
-        uses: bitwarden/gh-actions/get-keyvault-secrets@f1125802b1ccae8c601d7c4f61ce39ea254b10c8
-        with:
-          keyvault: "bitwarden-ci"
-          secrets: "devops-alerts-slack-webhook-url"
-
-      - name: Notify Slack on failure
-        uses: act10ns/slack@ed1309ab9862e57e9e583e51c7889486b9a00b0f  # v2.0.0
-        if: failure()
-        env:
-          SLACK_WEBHOOK_URL: ${{ steps.retrieve-secrets.outputs.devops-alerts-slack-webhook-url }}
-        with:
-          status: ${{ job.status }}
+          #  build-safari:
+          #    name: Build Safari
+          #    runs-on: macos-11
+          #    needs:
+          #      - setup
+          #      - locales-test
+          #    env:
+          #      _BUILD_NUMBER: ${{ needs.setup.outputs.adj_build_number }}
+          #      _NODE_VERSION: ${{ needs.setup.outputs.node_version }}
+          #    steps:
+          #      - name: Checkout repo
+          #        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+          #
+          #      - name: Set up Node
+          #        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
+          #        with:
+          #          cache: 'npm'
+          #          cache-dependency-path: '**/package-lock.json'
+          #          node-version: ${{ env._NODE_VERSION }}
+          #
+          #      - name: Print environment
+          #        run: |
+          #          node --version
+          #          npm --version
+          #
+          #      - name: Decrypt secrets
+          #        env:
+          #          DECRYPT_FILE_PASSWORD: ${{ secrets.DECRYPT_FILE_PASSWORD }}
+          #        run: |
+          #          mkdir -p $HOME/secrets
+          #          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
+          #            --output "$HOME/secrets/bitwarden-desktop-key.p12" \
+          #            "$GITHUB_WORKSPACE/.github/secrets/bitwarden-desktop-key.p12.gpg"
+          #          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
+          #            --output "$HOME/secrets/appstore-app-cert.p12" \
+          #            "$GITHUB_WORKSPACE/.github/secrets/appstore-app-cert.p12.gpg"
+          #          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
+          #            --output "$HOME/secrets/appstore-installer-cert.p12" \
+          #            "$GITHUB_WORKSPACE/.github/secrets/appstore-installer-cert.p12.gpg"
+          #          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
+          #            --output "$HOME/secrets/devid-app-cert.p12" \
+          #            "$GITHUB_WORKSPACE/.github/secrets/devid-app-cert.p12.gpg"
+          #          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
+          #            --output "$HOME/secrets/devid-installer-cert.p12" \
+          #            "$GITHUB_WORKSPACE/.github/secrets/devid-installer-cert.p12.gpg"
+          #          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
+          #            --output "$HOME/secrets/macdev-cert.p12" \
+          #            "$GITHUB_WORKSPACE/.github/secrets/macdev-cert.p12.gpg"
+          #          gpg --quiet --batch --yes --decrypt --passphrase="$DECRYPT_FILE_PASSWORD" \
+          #            --output "$HOME/secrets/bitwarden_desktop_appstore.provisionprofile" \
+          #            "$GITHUB_WORKSPACE/.github/secrets/bitwarden_desktop_appstore.provisionprofile.gpg"
+          #
+          #      - name: Set up keychain
+          #        env:
+          #          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+          #          DESKTOP_KEY_PASSWORD: ${{ secrets.DESKTOP_KEY_PASSWORD }}
+          #          DEVID_CERT_PASSWORD: ${{ secrets.DEVID_CERT_PASSWORD }}
+          #          APPSTORE_CERT_PASSWORD: ${{ secrets.APPSTORE_CERT_PASSWORD }}
+          #          MACDEV_CERT_PASSWORD: ${{ secrets.MACDEV_CERT_PASSWORD }}
+          #          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
+          #        run: |
+          #          security create-keychain -p $KEYCHAIN_PASSWORD build.keychain
+          #          security default-keychain -s build.keychain
+          #          security unlock-keychain -p $KEYCHAIN_PASSWORD build.keychain
+          #          security set-keychain-settings -lut 1200 build.keychain
+          #          security import "$HOME/secrets/bitwarden-desktop-key.p12" -k build.keychain -P $DESKTOP_KEY_PASSWORD \
+          #            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
+          #          security import "$HOME/secrets/devid-app-cert.p12" -k build.keychain -P $DEVID_CERT_PASSWORD \
+          #            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
+          #          security import "$HOME/secrets/devid-installer-cert.p12" -k build.keychain -P $DEVID_CERT_PASSWORD \
+          #            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
+          #          security import "$HOME/secrets/appstore-app-cert.p12" -k build.keychain -P $APPSTORE_CERT_PASSWORD \
+          #            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
+          #          security import "$HOME/secrets/appstore-installer-cert.p12" -k build.keychain -P $APPSTORE_CERT_PASSWORD \
+          #            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
+          #          security import "$HOME/secrets/macdev-cert.p12" -k build.keychain -P $MACDEV_CERT_PASSWORD \
+          #            -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
+          #          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PASSWORD build.keychain
+          #
+          #      - name: NPM setup
+          #        run: npm ci
+          #        working-directory: ./
+          #
+          #      - name: Build Safari extension
+          #        run: npm run dist:safari
+          #        working-directory: apps/browser
+          #
+          #      - name: Zip Safari build artifact
+          #        run: |
+          #          cd apps/browser/dist
+          #          zip dist-safari.zip ./Safari/**/build/Release/safari.appex -r
+          #          pwd
+          #          ls -la
+          #
+          #      - name: Upload Safari artifact
+          #        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
+          #        with:
+          #          name: dist-safari-${{ env._BUILD_NUMBER }}.zip
+          #          path: apps/browser/dist/dist-safari.zip
+          #          if-no-files-found: error
+          #
+          #  crowdin-push:
+          #    name: Crowdin Push
+          #    if: github.ref == 'refs/heads/master'
+          #    runs-on: ubuntu-22.04
+          #    needs:
+          #      - build
+          #      - build-safari
+          #    steps:
+          #      - name: Checkout repo
+          #        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+          #
+          #      - name: Login to Azure
+          #        uses: Azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.7
+          #        with:
+          #          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
+          #
+          #      - name: Retrieve secrets
+          #        id: retrieve-secrets
+          #        uses: bitwarden/gh-actions/get-keyvault-secrets@f1125802b1ccae8c601d7c4f61ce39ea254b10c8
+          #        with:
+          #          keyvault: "bitwarden-ci"
+          #          secrets: "crowdin-api-token"
+          #
+          #      - name: Upload Sources
+          #        uses: crowdin/github-action@ee4ab4ea2feadc0fdc3b200729c7b1c4cf4b38f3 # v1.11.0
+          #        env:
+          #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          #          CROWDIN_API_TOKEN: ${{ steps.retrieve-secrets.outputs.crowdin-api-token }}
+          #          CROWDIN_PROJECT_ID: "268134"
+          #        with:
+          #          config: apps/browser/crowdin.yml
+          #          crowdin_branch_name: master
+          #          upload_sources: true
+          #          upload_translations: false
+          #
+          #  check-failures:
+          #    name: Check for failures
+          #    if: always()
+          #    runs-on: ubuntu-22.04
+          #    needs:
+          #      - cloc
+          #      - setup
+          #      - locales-test
+          #      - build
+          #      - build-safari
+          #      - crowdin-push
+          #    steps:
+          #      - name: Check if any job failed
+          #        if: ${{ (github.ref == 'refs/heads/master') || (github.ref == 'refs/heads/rc') }}
+          #        env:
+          #          CLOC_STATUS: ${{ needs.cloc.result }}
+          #          SETUP_STATUS: ${{ needs.setup.result }}
+          #          LOCALES_TEST_STATUS: ${{ needs.locales-test.result }}
+          #          BUILD_STATUS: ${{ needs.build.result }}
+          #          SAFARI_BUILD_STATUS: ${{ needs.build-safari.result }}
+          #          CROWDIN_PUSH_STATUS: ${{ needs.crowdin-push.result }}
+          #        run: |
+          #          if [ "$CLOC_STATUS" = "failure" ]; then
+          #              exit 1
+          #          elif [ "$SETUP_STATUS" = "failure" ]; then
+          #              exit 1
+          #          elif [ "$LOCALES_TEST_STATUS" = "failure" ]; then
+          #              exit 1
+          #          elif [ "$BUILD_STATUS" = "failure" ]; then
+          #              exit 1
+          #          elif [ "$SAFARI_BUILD_STATUS" = "failure" ]; then
+          #              exit 1
+          #          elif [ "$CROWDIN_PUSH_STATUS" = "failure" ]; then
+          #              exit 1
+          #          fi
+          #
+          #      - name: Login to Azure - Prod Subscription
+          #        uses: Azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.7
+          #        if: failure()
+          #        with:
+          #          creds: ${{ secrets.AZURE_KV_CI_SERVICE_PRINCIPAL }}
+          #
+          #      - name: Retrieve secrets
+          #        id: retrieve-secrets
+          #        if: failure()
+          #        uses: bitwarden/gh-actions/get-keyvault-secrets@f1125802b1ccae8c601d7c4f61ce39ea254b10c8
+          #        with:
+          #          keyvault: "bitwarden-ci"
+          #          secrets: "devops-alerts-slack-webhook-url"
+          #
+          #      - name: Notify Slack on failure
+          #        uses: act10ns/slack@ed1309ab9862e57e9e583e51c7889486b9a00b0f  # v2.0.0
+          #        if: failure()
+          #        env:
+          #          SLACK_WEBHOOK_URL: ${{ steps.retrieve-secrets.outputs.devops-alerts-slack-webhook-url }}
+          #        with:
+          #          status: ${{ job.status }}
